version: '3.9'

services:
  lab:
    env_file: .env
    build:
      context: ./lab
      args:
        - PASSWD=${PASSWD}
    ports:
      - "8888:8888"
    volumes:
      - work:/home/jovyan/work


volumes:
  work: